version: '3'
services:
# 先启动3个zookeeper
    zoo1:
        image: zookeeper
        restart: always
        container_name: zk01
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zk01:2888:3888 server.2=zk02:2888:3888 server.3=zk03:2888:3888

    zoo2:
        image: zookeeper
        restart: always
        container_name: zk02
        ports:
            - "2182:2181"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zk01:2888:3888 server.2=zk02:2888:3888 server.3=zk03:2888:3888

    zoo3:
        image: zookeeper
        restart: always
        container_name: zk03
        ports:
            - "2183:2181"
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zk01:2888:3888 server.2=zk02:2888:3888 server.3=zk03:2888:3888
# 接着启动3个 data node |  journal node
    jnnode01:
        container_name: slave01
        image: gaodch/hadoop
        restart: always
        hostname: slave01
        port:
            - "50075:50075" 
    jnnode02:
        container_name: slave02
        image: gaodch/hadoop
        restart: always
        hostname: slave02
           - "50076:50075"
    jnnode03:
        container_name: slave03
        image: gaodch/hadoop
        restart: always 
        hostname: slave03  
           - "50077:50075" 
# 启动一个namenode
    namenode01:
        container_name: master01
        image: gaodch/hadoop
        restart: always    
        ports:
            - "50070:50070"
            - "8080:8088"
            - "19888:19888"
    namenode02:
        container_name: master02  
        image: gaodch/hadoop
        restart: always 
        ports:
            - "50071:50070"
            - "8081:8088"
            - "19889:19888"